spring:
    application:
        name: cube-gateway
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
            routes:
                - id: CUBE-MS-USER-AUTH
                  uri: lb://CUBE-MS-USER
                  predicates:
                      - Path=/v1/auth/**

                - id: CUBE-MS-USER-CUSTOMER
                  uri: lb://CUBE-MS-USER
                  predicates:
                      - Path=/v1/customer/**
                  filters:
                      - AuthenticationFilter

                - id: CUBE-MS-ORDER
                  uri: lb://CUBE-MS-ORDER
                  predicates:
                      - Path=/v1/order/**
                  filters:
                      - AuthenticationFilter
            globalcors:
                cors-configurations:
                    '[/**]':
                        allowedOrigins: ["https://cube.matheus-junior.xyz"]
                        allowedMethods: "*"
                        allowedHeaders: "*"
                        allowCredentials: "true"
        loadbalancer:
            ribbon:
                enabled: false
    config:
        import: optional:configserver:http://localhost:8888
token:
    secret: "${JWT_SECRET}"
eureka:
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: ${EUREKA_URL:https://cube-ms-eureka.onrender.com/eureka/}
server:
    port: ${PORT:8080}
    error:
        include-message: always
