spring:
    application:
        name: cube-gateway

    cloud:
        openfeign:
            client:
                config:
                    cubeMsUser:
                        url: http

    config:
        import: optional:configserver:http://localhost:8888

server:
    port: 8089
    error:
        include-message: always